require "app/nokia.rb"
require "app/actors.rb"
require "app/actors/background.rb"
require "app/actors/bug.rb"
require "app/actors/splat.rb"
require "app/actors/reticle.rb"
require "app/actors/paw.rb"
require "app/screens/game.rb"
require "app/screens/title.rb"
require "app/state.rb"
require "app/sprite.rb"
require "app/debug.rb"
require "app/ease.rb"

# This one has to be last.
require "app/tick.rb"
